apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: flask
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - env:
        - name: PLATFORM
          value: dev
        image: pankaj2934/flask-gitops:16
        name: flask
        ports:
        - containerPort: 5000
